stages:
  - run_scanner

run_scanner_job:
  stage: run_scanner
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python phase1_scanner.py
  artifacts:
    paths:
      - result.txt
      - result.html
    expire_in: 1 week
